In [26]:
import pandas as pd

In [27]:
data={
    'Name':['Alice','bob','charlie'],
    'age':[25,56,35],
    'city':['new york','los angels','chicago']
}
data

{'Name': ['Alice', 'bob', 'charlie'],
 'age': [25, 56, 35],
 'city': ['new york', 'los angels', 'chicago']}

In [28]:
df=pd.DataFrame(data)
df

      Name  age        city
0    Alice   25    new york
1      bob   56  los angels
2  charlie   35     chicago

In [29]:
df[['Name','age']] ## selecting multiple columns from the dataframe

      Name  age
0    Alice   25
1      bob   56
2  charlie   35

In [30]:
df.loc[1]  ##selecting a single row from the dataframe using loc

Name           bob
age             56
city    los angels
Name: 1, dtype: object

In [31]:
df.iloc[1] ##electing a single row from the dataframe using iloc

Name           bob
age             56
city    los angels
Name: 1, dtype: object

# # setting individual columns as a index

In [32]:
# df.set_index('Name',inplace=True) 
# df

### setting new data as index

In [55]:
df.index=['a','b','c']
df.index

Index(['a', 'b', 'c'], dtype='str')

In [56]:
df.iloc[1] ##position

Name          bob
NAME_UPPER    BOB
Name: b, dtype: str

In [57]:
df.loc['b'] ##labels

Name          bob
NAME_UPPER    BOB
Name: b, dtype: str

In [58]:
del df['city']
df

KeyError: 'city'

In [ ]:
df=df.drop(['age'],axis=1)
df

      Name
a    Alice
b      bob
c  charlie

In [ ]:
new_column={
    'Name':'Name',
    'Age':'Age'
}
df.rename(columns=new_column,inplace=True)
df

      Name
a    Alice
b      bob
c  charlie

In [ ]:
uppercase_values=df['Name'].str.upper()
uppercase_values

a      ALICE
b        BOB
c    CHARLIE
Name: Name, dtype: str

In [ ]:
df['NAME_UPPER']=df['Name'].str.upper()
df

      Name NAME_UPPER
a    Alice      ALICE
b      bob        BOB
c  charlie    CHARLIE

## performing data Anlaysis over some Random Data

CSV Datafile

In [ ]:
data =pd.read_csv('data.csv') ## reading a csv file into a dataframe using the read_csv method
data

      Name   Age         City    Position
0    Alice  30.0     New York     Manager
1      Bob  25.0  Los Angeles   Developer
2  Charlie   NaN      Chicago     Analyst
3    David  28.0      Houston    Designer
4      Eve  32.0      Phoenix  Consultant

In [64]:
data.isnull().sum()

Name        0
Age         1
City        0
Position    0
dtype: int64

In [65]:
data.notnull().sum()

Name        5
Age         4
City        5
Position    5
dtype: int64

dropping the rows which has null values

In [66]:
data.dropna()

    Name   Age         City    Position
0  Alice  30.0     New York     Manager
1    Bob  25.0  Los Angeles   Developer
3  David  28.0      Houston    Designer
4    Eve  32.0      Phoenix  Consultant

dropping the coilumns which has null values

In [67]:
data.dropna(axis=1)

      Name         City    Position
0    Alice     New York     Manager
1      Bob  Los Angeles   Developer
2  Charlie      Chicago     Analyst
3    David      Houston    Designer
4      Eve      Phoenix  Consultant

In [68]:
data

      Name   Age         City    Position
0    Alice  30.0     New York     Manager
1      Bob  25.0  Los Angeles   Developer
2  Charlie   NaN      Chicago     Analyst
3    David  28.0      Houston    Designer
4      Eve  32.0      Phoenix  Consultant

Instead of dropping just fill the full values with actual values

In [70]:
data.fillna(0,inplace=True)

      Name   Age         City    Position
0    Alice  30.0     New York     Manager
1      Bob  25.0  Los Angeles   Developer
2  Charlie   0.0      Chicago     Analyst
3    David  28.0      Houston    Designer
4      Eve  32.0      Phoenix  Consultant

In [71]:
data.fillna(data['Age'].mean(),inplace=True)
data

      Name   Age         City    Position
0    Alice  30.0     New York     Manager
1      Bob  25.0  Los Angeles   Developer
2  Charlie   0.0      Chicago     Analyst
3    David  28.0      Houston    Designer
4      Eve  32.0      Phoenix  Consultant

In [72]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      5 non-null      str
 1   Age       5 non-null      float64
 2   City      5 non-null      str
 3   Position  5 non-null      str
dtypes: float64(1), str(3)
memory usage: 292.0 bytes

In [73]:
data.describe()

             Age
count   5.000000
mean   23.000000
std    13.114877
min     0.000000
25%    25.000000
50%    28.000000
75%    30.000000
max    32.000000

In [74]:
data.head()

      Name   Age         City    Position
0    Alice  30.0     New York     Manager
1      Bob  25.0  Los Angeles   Developer
2  Charlie   0.0      Chicago     Analyst
3    David  28.0      Houston    Designer
4      Eve  32.0      Phoenix  Consultant

In [75]:
data.tail()

      Name   Age         City    Position
0    Alice  30.0     New York     Manager
1      Bob  25.0  Los Angeles   Developer
2  Charlie   0.0      Chicago     Analyst
3    David  28.0      Houston    Designer
4      Eve  32.0      Phoenix  Consultant